theme: jekyll-theme-cayman
title: Personalized Image Enhancement Using NeuralSpline Color Transforms
description: A new method for fast adaptation to a new user's image enhancement style.
show_downloads: "true"
google_analytics: UA-159944018-1
